import numpy as np
import matplotlib.pyplot as plt
loss_get = np.load("../loss_data/ddpm_loss_get_2.npy")
print(loss_get)
x = np.arange(len(loss_get))
loss_get = np.array(loss_get)
plt.plot(x, loss_get)
plt.title("ddpm_Loss")
plt.show()
val_loss_get = np.load("../loss_data/ddpm_val_loss_get_2.npy")
print(val_loss_get)
x = np.arange(len(val_loss_get))
loss_get = np.array(val_loss_get)
plt.plot(x, val_loss_get)
plt.title("val_Loss")
plt.show()
# loss_get = np.load("../loss_data/unet_loss_get.npy")
# print(loss_get)
# x = np.arange(len(loss_get))
# loss_get = np.array(loss_get)
# plt.plot(x, loss_get)
# plt.title("unet_Loss")
# plt.show()
# val_loss_get = np.load("../loss_data/unet_val_loss_get.npy")
# print(val_loss_get)
# x = np.arange(len(val_loss_get))
# loss_get = np.array(val_loss_get)
# plt.plot(x, val_loss_get)
# plt.title("unet_val_Loss")
# plt.show()